### ISSUE TITLE
上财等两百多所学校未收录

### ISSUE THREAD

**Issue by Qaplagzy** [xioajiumi/Chinese_Universities#1]
你好，这是个非常棒的库，在我的survey过程中发现。注意到校徽是由软科网产生的，但学校名录只覆盖了主榜的学校，能覆盖总榜的学校吗？谢谢

**Comment by xioajiumi** [comment]
你好！谢谢你的支持，也谢谢你提出的issue。由于个人精力原因我只做了主榜的高校信息统计，3个月内暂时无法继续增添新的数据，望体谅。
如果你急用相关数据的话，可以试试采用[这个网站](http://daxue.menggy.com/140/%E8%BD%AF%E7%A7%91%E4%B8%AD%E5%9B%BD%E5%A4%A7%E5%AD%A6%E6%8E%92%E5%90%8D/442/%E4%B8%8A%E6%B5%B7%E8%B4%A2%E7%BB%8F%E5%A4%A7%E5%AD%A6)的数据。站主的网站覆盖高校更多，排名更为丰富，通过构造请求信息应该满足你的需求。
教育部的[这个文件](http://www.moe.gov.cn/jyb_xxgk/s5743/s5744/A03/202110/t20211025_574874.html)覆盖了全国基本上所有的高校基本信息，也许会对你有用。
——————————————————————————————
另外，我本人的原始思路是通过解析软科的HTML元素来得到大学名字、logo和学校类型等信息，然后通过调用Google搜索API来搜索大学名字进而得到其官网链接进行数据整合。这是一种比较笨的方法，但希望对你DIY有所帮助。

**Comment by Qaplagzy** [comment]
明白，看得出来这是一个庞大的工作。目前我的需求是建立一个更全一些的“名称-logo“库，也就是扩充一下repo里的logo.7z，请问这部分内容你是怎么获得的 是用jquery嘛 还是 python 能提供一下嘛

**Comment by xioajiumi** [comment]
爬取思路、方法和可能需要的文件我放在了[这里](https://github.com/xioajiumi/useless/blob/main/%E5%A6%82%E4%BD%95%E7%88%AClogo.7z)，更多的说明在压缩包内。
祝你顺利😀

**Comment by Qaplagzy** [comment]
感谢，我的短期需求已经得到解决。但我坚持认为这是一个很棒的库，当时survey前就想过没有现成的库就自己维护一个，很有意义，后来发现已经有人做了很多的努力在做这件事。后续有机会也会参与维护这个库，谢谢

**Comment by xioajiumi** [comment]
共勉(ง •_•)ง
